### ISSUE TITLE
Why this example not generating the desired output to me?

### ISSUE THREAD

**Issue by vivekgurukul1982** [confluentinc/examples#95] opened 2017-02-06 23:38 UTC
I am trying these examples and running in HDInsight Kafka Cluster using the below command:

java -jar jarName.jar class ClassName

It is not taking the input from input topic and not writing the same data to output topic, any suggestion what needs to be done to make it work?

**Comment by miguno** [comment] 2017-02-07 11:09
Vivek, I think you have asked the same question in the Confluent mailing list:
https://groups.google.com/d/msg/confluent-platform/y_yMY-m2Jhw/QDmFD3hSDgAJ

Most probably, as mentioned in the discussion above, the problem is related to your HDInsight environment.  Since we already have the conversation in the mailing list I will close this question.

**Closed by miguno** 2017-02-07 11:09 UTC

**Comment by vivekgurukul1982** [comment] 2017-02-07 18:16
Thanks Miguno for your quick response, If I can get the root cause or any thought how to resolve this issue, it would be great !
