### ISSUE TITLE
Different de/serializer for input and output of stream 

### ISSUE THREAD

**Issue by jozi-k** [confluentinc/examples#73] opened 2016-10-13 13:36 UTC
I am trying to play with kafka-stream in following way:
Input topic A contains avro records for users in format num: Int, name: String. Deserialization of values is specified in properties as GenericAvroSerde, which is part of examples.

Output topic B should produce total sum of nums per name. Main part of my code looks like this (be aware of scala there):

```scala
val users: KStream[String, GenericRecord] = builder.stream("avro-topic-A")
val valuesMapped: KStream[String, User] = users.mapValues(createUser)
val names: KStream[String, Integer] = valuesMapped.map { (_, v) => (v.name, v.num)}
val agg: KTable[String, Integer] = names.reduceByKey((x, y) => x + y, "Aggregate")
agg.to(Serdes.String(), Serdes.Integer(), "avro-topic-B")
```

`createUser` method takes `GenericRecord` and returns case class `User(sum: Int, name: String)`. Now, the output I get is as follows:

```
[error] (StreamThread-1) java.lang.ClassCastException: java.lang.Integer cannot be cast to org.apache.avro.generic.GenericRecord
java.lang.ClassCastException: java.lang.Integer cannot be cast to org.apache.avro.generic.GenericRecord 
at serde.GenericAvroSerializer.serialize(GenericAvroSerializer.java:10)
at org.apache.kafka.streams.state.StateSerdes.rawValue(StateSerdes.java:176)....
```

This sounds like GenericAvroSerializer is used for Integer serialization which is in contrast with my explicit specification, see last line of my code. Is it bug or I just misunderstood usage of serializers?

**Comment by mjsax** [comment] 2016-10-13 18:05
I think the problem is the following: In your source topic, you use String/GenericRecord as types, and this type information is kept for the `reduceByKey` step (it does write in an internal changelog topic in the background). There error is in `StateSerdes` and not in `agg.to(...)`. This might be a bug in Kafka Streams -- what version do you use?

I think a workaround is, to do an explicit re-partitioning step after your `map` and before your `reduceByKey` via `through(...)` and specify the correct Serdes within `through`. Keep in mind, that it is recommended to create topics used in through() should be created manually before starting the Streams application.

Let me know if this works for you.

**Comment by jozi-k** [comment] 2016-10-14 09:08
Thanks for hints @mjsax. 

To be sure where error occurs I added line
`agg.foreach((k,v) => println(s"key is : $k, value is $v"))` 
right before `agg.to()`. As a result I got all my records printed and after cca 20 seconds the error is printed. See full stack trace:
```
key is : Martin Odersky, value is 1
key is : Erik Meijer, value is 2
[error] (StreamThread-1) java.lang.ClassCastException: java.lang.Integer cannot be cast to org.apache.avro.generic.GenericRecord
java.lang.ClassCastException: java.lang.Integer cannot be cast to org.apache.avro.generic.GenericRecord
        at serde.GenericAvroSerializer.serialize(GenericAvroSerializer.java:10)
        at org.apache.kafka.streams.state.StateSerdes.rawValue(StateSerdes.java:176)
        at org.apache.kafka.streams.state.internals.RocksDBStore.flushCache(RocksDBStore.java:381)
        at org.apache.kafka.streams.state.internals.RocksDBStore.flush(RocksDBStore.java:424)
        at org.apache.kafka.streams.state.internals.MeteredKeyValueStore.flush(MeteredKeyValueStore.java:165)
        at org.apache.kafka.streams.processor.internals.ProcessorStateManager.flush(ProcessorStateManager.java:332)
        at org.apache.kafka.streams.processor.internals.StreamTask.commit(StreamTask.java:252)
        at org.apache.kafka.streams.processor.internals.StreamThread.commitOne(StreamThread.java:446)
        at org.apache.kafka.streams.processor.internals.StreamThread.commitAll(StreamThread.java:434)
        at org.apache.kafka.streams.processor.internals.StreamThread.maybeCommit(StreamThread.java:422)
        at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:340)
        at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:218)
```

I use kafka-streams version 0.10.0.1. Adding `through(stringSerde, intSerde, "temp-topic")` where temp-topic is created manually did not help, i.e. I got the same error. It is suspicious to me that there is 20 seconds window between printing stream values and getting error.

Hope this investigation helps. I can try any other test, just let me know.

**Comment by miguno** [comment] 2016-10-14 09:30
@jozi-k : Can you share the full code of your example, rather than just the few lines you included above?  Notably I'd be interested in seeing the configuration of the application (`StreamsConfig` and such).

**Comment by miguno** [comment] 2016-10-14 09:37
```
[error] (StreamThread-1) java.lang.ClassCastException: java.lang.Integer cannot be cast to org.apache.avro.generic.GenericRecord
java.lang.ClassCastException: java.lang.Integer cannot be cast to org.apache.avro.generic.GenericRecord
        at serde.GenericAvroSerializer.serialize(GenericAvroSerializer.java:10)
        at org.apache.kafka.streams.state.StateSerdes.rawValue(StateSerdes.java:176)
```

I am asking about `GenericAvroSerializer` because, for the class of the same name that is included in this GitHub repository, line 10 is still part of the license header.

**Comment by miguno** [comment] 2016-10-14 09:47
Also, while we're at it: You said you have a case class `User(sum: Int, name: String)`.

Note that `scala.Int` is different from `java.lang.Integer`, and Kafka's `Serdes.Integer()` operates on `java.lang.Integer` only.  Sometimes you will run into Scala-Java interop issues such as `scala.Int` vs. `java.lang.Integer` that also affect Kafka Streams.

**Comment by jozi-k** [comment] 2016-10-14 10:11
I changed case class to include java Integer. I use GenericAvroSerializer from the exercises, which is licensed to your company. I have no intention to say it is my own code. I am just trying to play with your library.

See the full code below, most of it is inspired by your java examples, trying to run them in scala.
```scala
case class User(sum: Integer, name: String)

object AvroStreams {
  def main(args: Array[String]): Unit = {
    val builder = new KStreamBuilder

    val users: KStream[String, GenericRecord] = builder.stream("avro-bin")

    val stringSerde = Serdes.String()
    val intSerde = Serdes.Integer()

    val valuesMapped: KStream[String, User] = users.mapValues(createUser)
    val names: KStream[String, Integer] = valuesMapped.map { (_, v) => (v.name, v.sum)}
    val temp = names.through(stringSerde, intSerde, "avro-temp")

    val agg: KTable[String, Integer] = temp.reduceByKey((s1, s2) => s1 + s2, "Aggregate")
    agg.foreach((k,v) => println(s"key is : $k, value is $v"))

    agg.to(stringSerde, intSerde, "avro-aggregate")

    val props = new Properties()
    props.put("bootstrap.servers", "localhost:9092")
    props.put("schema.registry.url", "http://localhost:8081")
    props.put("metadata.broker.list", "localhost:9092")
    props.put("message.send.max.retries", "5")
    props.put("request.required.acks", "-1")
    props.put("serializer.class", "kafka.serializer.DefaultEncoder")
    props.put("client.id", UUID.randomUUID().toString)
    props.put(StreamsConfig.APPLICATION_ID_CONFIG, "avro-aggregation-scala-example")
    props.put(StreamsConfig.KEY_SERDE_CLASS_CONFIG, Serdes.String().getClass.getName)
    props.put(StreamsConfig.VALUE_SERDE_CLASS_CONFIG, classOf[GenericAvroSerde])
    
    val stream = new KafkaStreams(builder, props)
    stream.start()
  }

  def createUser(r: GenericRecord): User = {
    val sum = r.get("sum").asInstanceOf[Integer]
    val name = r.get("name").toString
    User(sum, name)
  }
}
```

**Comment by miguno** [comment] 2016-10-14 11:00
> I changed case class to include java Integer. I use GenericAvroSerializer from the exercises, which is licensed to your company. I have no intention to say it is my own code. I am just trying to play with your library.

Oh, I think I wasn't clear.  I asked the question about `GenericAvroSerializer` because I looked at the line in your stacktrace (line 10), but version of of `GenericAvroSerializer` in this repository doesn't have any code at line 10.  So, in your code, what are the contents of line 10?

**Comment by jozi-k** [comment] 2016-10-14 12:08
Ah, okay. It is line with class declaration:
`public class GenericAvroSerializer implements Serializer<GenericRecord> {`

By coincidence, I looked at topic (used in through() method call) via kafka-console-consumer and I see it contains some binary encoded values, the same applies to output topic, which is very confusing. When I wrote my own producer in scala and used Serdes.Integer() for values, the output of kafka-console-consumer was not shown in binary format.

Well, it is getting complicated, if you wish I can post all code from my repo to github so you can play with it.

**Comment by miguno** [comment] 2016-10-14 12:18
> Well, it is getting complicated, if you wish I can post all code from my repo to github so you can play with it.

Feel free to do that.

**Comment by miguno** [comment] 2016-10-14 13:37
@jozi-k The following should fix your problem.

Change:

```scala
    val agg: KTable[String, Integer] = temp.reduceByKey((s1, s2) => s1 + s2, "Aggregate")
```

to:

```scala
    val agg: KTable[String, Integer] = temp.reduceByKey((s1, s2) => s1 + s2, stringSerde, intSerde, "Aggregate")
```

Full(ish) code:

```scala
    val stringSerde: Serde[String] = Serdes.String
    val intSerde: Serde[Integer] = Serdes.Integer

    val users: KStream[String, GenericRecord] = builder.stream(inputTopic)
    val valuesMapped: KStream[String, User] = users.mapValues(createUser)
    import KeyValueImplicits._
    val names: KStream[String, Integer] = valuesMapped.map { (_, v) => (v.name, v.sum) }
    val temp = names.through(stringSerde, intSerde, rekeyedIntermediateTopic)
    val agg: KTable[String, Integer] = temp.reduceByKey((s1, s2) => s1 + s2, stringSerde, intSerde, "Aggregate")
    agg.foreach((k, v) => println(s"Computed: key=$k value=$v"))
    agg.to(stringSerde, intSerde, outputTopic)

    val streams: KafkaStreams = new KafkaStreams(builder, streamsConfiguration)
    streams.start()
```

**Comment by miguno** [comment] 2016-10-14 13:48
And, for future users of upcoming Kafka 0.10.1, here's the corresponding fix for this newer version of Kafka where `reduceByKey` was split into `groupByKey` and `reduce`:

```scala
    val agg: KTable[String, Integer] = names.groupByKey(stringSerde, intSerde).reduce((s1, s2) => s1 + s2, "Aggregate")
```

**Comment by jozi-k** [comment] 2016-10-14 13:48
Okay, thanks for hint, will try it.

I have published my code here: https://github.com/jozi-k/playing-with-kafka-streams. My primary problem is resolved, I can use streams, read from avro encode format and write integers to plain kafka topic. However, after it I get exception as I described earlier. I will try to apply your suggestions and see if it helps.

**Comment by jozi-k** [comment] 2016-10-14 14:31
Confirm it is working, even without `through()` method.

**Comment by miguno** [comment] 2016-10-14 16:49
Happy to hear that @jozi-k !

**Closed by miguno** 2016-10-14 16:49 UTC
Labels: question
