### ISSUE TITLE
Window#until() keeps processing records after retention time expires.

### ISSUE THREAD

**Issue by jozi-k** [confluentinc/examples#76] opened 2016-10-20 14:58 UTC
I wrote small test to see how windowing works. My main concern was to try late arrival feature, so I use my own TimeExtractor and every second I generate 2 kinds of messages whose timestamp is:
a) fixed at some point in history
b) generated dynamically via `LocalDateTime.now()`
Then in stream processing I created 5s hopping windows, with retention time 15s:
 `TimeWindows.of("Window", 5 * 1000L).advanceBy(5 * 1000L).until(15 * 1000L)`
In my code I count number of records with same key. All records I generate are mapped to same key. At the beginning it behaves correctly, I get results like 1, 2, 3, 4, 5, 1, 2, 6, 7, 8, 1, 9, 10, 11, 12, 1, 13, 14...
But you can see that after 15 seconds window state is not closed and keeps updating it after retention period expired. I get the expected output (no number greater than 5) after 3 minutes of running my application: ..., 1, 2, 91, 3, 4, 92, 1, 2, 1, 3, 1, 2, 3, 4, 5, 1...

All code with explanation can be found [here](https://github.com/jozi-k/playing-with-kafka-streams), when trying to run it please change line 23 in AvroProducer.scala

Thanks for any feedback guys.

**Comment by mjsax** [comment] 2016-10-20 18:15
I cannot follow completely. If you define a 5 second hopping window, the counts for the hopping windows (only considering the regular, ie, not fixed timed records, sent in 1 second interval) should be 1,2,3,4,5,1,2,3,4,5,... etc. Right?

So how can you get counts larger than 5 if you send old records with fixed point in time that is before the timestamps of you "regular" records? Or do you have a fixed point in time, that is not before the first "regular" record, so that you fixed time records are part of the same windows as the "regular one"?

So if you insert old data with fixed timestamp, the initial behavior depends if this timestamp is before or after the retention time.

Before (ie, older than retention time): For this case, each record will start a new window that only contains this record, the aggregation will be computed (ie, count output = 1) and the window will be discarded because it is older than retention time.

In between (ie, newer then retention time but older than all other timestamps): New window will be created and regularly processed. As data is going in, it will keep counting up to max 15 (depending when you did start the window, ie, how old you record are) -- after that, retention time passed and window will be discarded. Afterward, processing as in "before" case should happen.

Please clarify, if I did miss understand you question.

**Comment by jozi-k** [comment] 2016-10-20 19:07
You are right, I explained it in complicated way. My output was mix of fixed and current time records which were generated randomly. Let me try to reformulate the question.
a) Setting record timestamp to `System.currentTimeMillis()` produces 1,2,3,4,5,1,2,3,4,5,etc. as expected
b) Setting record timestamp to some fixed time in past, before window's retention time expiration produces 1,1,1,1,1,1,1,etc. as expected.
c) Setting record timestamp between fixed time in past and window's retention time expiration produces 1,2,3,4,5,6,7,...,180 (this case is weird, and this is my original question). To be sure we are on the same boat, if I start producing my records (only minutes and seconds are relevant) at 00:00. Timestamp of records is fixed at 00:02. I start my stream application at 00:00, first window should have start/end at 00:00/00:05 and expiration time at 00:15. However, what I see is open window until 03:00 (180 seconds). 
d) Setting record timestamp after window's expiration time have not been tried, I will do that tomorrow and let you know. Also I will update my repo to include only fixed times, not randomly generated fixed/current time.

**Comment by mjsax** [comment] 2016-10-20 20:17
For (c), do you process any other records than your fixed time records? If not, your window will no expire, because window retention is not bound to wall clock time, but to internally tracked "streams time" which depend on the record timestamps of the processed data. Thus, if you only send records with a fixed timestamp, "streams time" does not advance and thus windows are not discarded. In you case, it seems that you do send a record with larger timestamp after you did send 180 records with fixed timestamp, and this new record advanced "streams time" and triggers the deletion of the window. Could this be the case?

**Comment by jozi-k** [comment] 2016-10-21 06:50
Regarding c)
Okay, "streams time" really do not advance with fixed time records, you are right. This leads us back to my original question. Let us have 2 types of records, first one is produced every odd second with fixed time, other one is produced also every even second but with current wall time. So timestamps look like: 00:00, 00:01, 00:00, 00:03, 00:00, 00:05, etc. 
I created same window as described above. Records are counted by key which is same for all of them. What I expected was output like:
1,2,3,4,5 | 1,6,2,7,3  | 8,1,9,2,10 | 1,1,2,1,3 | 1,1,1,2,1 | etc... 
N.B. After third window, there should not be number bigger than 10 in output. What I actually get is:
...numbers up to 90... | 1,1,2,1,3 | 1,1,1,2,1 | etc...
So there are 90 pairs emitted in 2 seconds, i.e. 180s, until fixed time window is closed, which is contrary to what I set in `until()` method.

Regarding d)
Same situation with generating records as above, but this time I tried to set time of fixed records 1 minute in future, so it is:
01:00, 00:01, 01:00, 00:03, 01:00, 00:05...
Output topic looks like:
... 1,117,2,118,3 | 119,1,120,2,121 | 1,1,2,1,3 | 1,1,1,2,1 etc.
This time, window was closed again 3 minutes after fixed timestamp, which is 4 minutes after I started my application (120*2/60). I guess there must be something done in background, which corresponds to those "magic" 3 minutes.

I updated example in my repo, so you can try for yourself. Just change line 20 in AvroProducer.scala to correct time for fixed record.

**Comment by mjsax** [comment] 2016-10-23 04:35
> 1,2,3,4,5 | 1,6,2,7,3 | 8,1,9,2,10 | 1,1,2,1,3 | 1,1,1,2,1 | etc... 
N.B. After third window, there should not be number bigger than 10 in output

Yes, agreed. Not sure, why you do get number up to 90. I will try to reproduce and dig deeper into it.

**Comment by mjsax** [comment] 2016-10-26 05:07
I dug into the code. We apply a lower bound on the retention time and your retention time is smaller than that. Thus, windows are kept longer than you did specify.

Basically, using window retention time guarantees that a window is kept for **at least** the specified amount of time. The semantics is not, that a window is deleted exactly after retention time passed.

Is this behavior a problem for you? Or do you just ask to understand the output?


In more detail, internally so-called segments are used. A segment provides memory to hold windows of a dedicated time period (ie, segments do not overlap and each window is stored in exactly one segment). When streams time advance we create new segments and old segments get deleted if not needed any more. Thus, segments also do have a retention time, which depends on the window retention time (we need to make sure we keep each segment until the window retention time of its assigned windows expires). However, we also apply a minimum segment retention time and thus it can happen for small window retention times, that a segment (and thus, the windows assigned to it) are kept longer than required by window retention time. And this is what happens in your case.

**Comment by jozi-k** [comment] 2016-10-26 13:44
It is not a problem, I was surprised it did not work for my example and I got the explanation. Maybe it would be nice to include that into the javadoc, so people are aware of it. Otherwise, this issue can be closed.

**Closed** 2016-10-26 17:57 UTC
